output_path: ./outputs/

# ----------------
# ----- Data -----
# ----------------
data:
  files: # if one is not none it will override the dirs location
    base: /Users/phil/Desktop/VITON-Sonder/data
    train: train_pairs.txt
    val: test_pairs.txt

  loaders:
    batch_size: 2
    shuffle: True
    num_workers: 3
  transforms:
    height: 192
    width: 256

# ------------------------
# ----- Model options -----
# ------------------------

model: 
  is_train: true
  use_gpu: true
  lambdas: {}
  loss_names: []
  verbose: false

# ------------------------
# ----- Comet options ----
# ------------------------


comet: 
  workspace: ""
  project_name: ""
  exp: None
  log_image_freq: 1000

# ------------------------
# ----- Train Params -----
# ------------------------
train:
  epochs: 1000
  lambdas: # scaling factors in the total loss
  log_level: 1 # 0: no log, 1: only aggregated losses, >1 detailed losses
  print_freq: 1 #How often to print iteration 
  save_im_freq: 100
  resume_checkpoint: false
  load_iter: 10000000000


# -----------------------------
# ----- Validation Params -----
# -----------------------------
val:
  max_log_images: 1
  save_im_freq: 1000
  store_images: false # write to disk on top of comet logging
