output_path: ./outputs/

# ----------------
# ----- Data -----
# ----------------
data:
  files: # if one is not none it will override the dirs location
    base: /path/to/data
    train: train.json
    val: val.json

  loaders:
    batch_size: 2
    shuffle: True
    num_workers: 3
  transforms:
    - name: hflip
      ignore: false
      p: 0.5
    - name: resize
      ignore: false
      new_size: 256
    - name: crop
      ignore: false
      height: 224
      width: 224
    - name: resize # ? this or change generator's output? Or resize larger then crop to 256?
      ignore: false
      new_size: 256


# ------------------------
# ----- Model options -----
# ------------------------

model: 
  is_train: true
  use_gpu: true
  lambdas: {}
  loss_names: []
  verbose: True

# ------------------------
# ----- Comet options ----
# ------------------------


comet: 
  workspace: ""
  project_name: ""
  exp: None
  log_image_freq: 1000

# ------------------------
# ----- Train Params -----
# ------------------------
train:
  epochs: 1000
  lambdas: # scaling factors in the total loss
  log_level: 1 # 0: no log, 1: only aggregated losses, >1 detailed losses
  save_im_freq: 100
  resume_checkpoint: false
  load_iter: 10000000000

# -----------------------------
# ----- Validation Params -----
# -----------------------------
val:
  max_log_images: 1
  save_im_freq: 1000
  store_images: false # write to disk on top of comet logging
